// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/aira-dashboard/Dashboard.tsx": () => import("../components/mockups/aira-dashboard/Dashboard.tsx"),
  "./components/mockups/templates/AIAgentDashboard-PfjOHC/Hive.tsx": () => import("../components/mockups/templates/AIAgentDashboard-PfjOHC/Hive.tsx")
};
